plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: pages #posts
    values:
      layout: single
      author_profile: false
      # read_time: true
      # comments: # true
      # share: true
      # related: true